### ISSUE TITLE
Missing cube_maps/Yokohama

### ISSUE THREAD

**Issue by asterite** [l3kn/raytracer-crystal#2]
I wanted to test that particular scene on my machine but it seems the file is missing (wasn't committed to git)

**Comment by l3kn** [comment]
The problem with these cube_maps is
that they (currently) need to be converted to .ppm
and because the original files are 2048x2048px
the files for all six sides would add up to ~200MB,
so I decided not to upload them to github.

I should have put the instructions about that in the readme,
not only in the source file of that scene.

In order to run this example:
1. Download the [set of cubemaps](http://www.humus.name/Textures/Yokohama3.zip)
2. Unzip the folder
3. Convert each .jpg to .ppm (uncompressed)
   e.g. using `convert negx.jpg -compress none negx.ppm` etc.
   (`convert` is part of the imagemagick)
4. Copy all six ppm files (`negx.ppm`, `negy.ppm`, `negz.ppm`, `posx.ppm`, `posy.ppm`, `posz.ppm`) to `cube_maps/Yokohama`

**Comment by asterite** [comment]
@l3kn Thank you! I'm at cube 264, soon I'll generate the animated gif 😸

**Comment by l3kn** [comment]
Awesome, let me know if you run into any problems or manage to create
a (decent looking) gif that is small enough to upload on github
(mine was 35mb large)
